### ISSUE TITLE
suggest rename of "space" parameter to "dimensions_file"

### ISSUE THREAD

**Issue by computron** [hackingmaterials/rocketsled#44]
since you are loading the "dimensions" parameter from a file, as far as I can tell?

**Comment by ardunn** [comment]
The space parameter is the file defining every entry in the search space (if specified). This option is only really useful when you have a discontinuous search domain which can't be described by (lower, upper) dimensions bounds or combinatorics. However, discontinuous search domains are common enough that I included it

**Comment by ardunn** [comment]
renamed to space_file instead to reflect meaning better via 518bc8087e4ac8511a9dc0bb8ddf7572b85022c7
