### ISSUE TITLE
make sure all instance attributes are only set in the __init__ method()

### ISSUE THREAD

**Issue by computron** [hackingmaterials/rocketsled#48]
e.g.:

self.enforce_sequential = self.get("enforce_sequential", True) should go in the __init__()

You can just define the __init__() of OptTask, call super on it to call the FireTaskBase.__init__(), then set whatever instance variables you like afterward to set defaults.

**Comment by computron** [comment]
defaults like:

        predictor = self.get('predictor', 'RandomForestRegressor')
        predargs = self.get('predictor_args', [])
        predkwargs = self.get('predictor_kwargs', {})

should also go in the __init__ method

**Comment by computron** [comment]
e.g., the "optimize()" function should be all about OPTIMIZATION, not setting up default parameters. The parameter values can all be determined and stored during __init__()

**Comment by ardunn** [comment]
done by commits leading up to 0ad6011e88569509ecea4382ea4b882d884cd162
