### ISSUE TITLE
tutorial rework

### ISSUE THREAD

**Issue by computron** [hackingmaterials/rocketsled#55]
Here is how I would re-work the tutorial.

* First, walk people through all the things they need in birds-eye overview, like you do. BUT walk them through this is in this order. What you need is:
    * a function (perhaps expensive) to optimize, that takes in a list of parameters x (called "_x", which can be a list of multiple input parameters) and returns an output value y (called "_y")
    * tell Rocketsled the bounds of the search space of possible values of the x vector to search over.
    * after each function evaluation Rocketsled will give you a new set of x to run. You should provide Rocketsled with a function to create a new "Workflow" object that can be run automatically to evaluate that x (we will cover this in more detail later).
* Next - create a new section for part (i) of the above and walk them through the code to define a FireTask with the function evaluation. I'd stick with the full custom FireTask way to do the function. Walk them through every line of this of this code (you can be brief - e.g., ``@explicit-serialize`` helps FireWorks find this code) and what it does (including things like the FWAction, etc).
* Next - create a new section for part (ii). This can just be a small section that explains the format of search dimensions and gives an example
* Next - create new section for part (iii). This section will have just the workflow creator function. You will need to take time to explain this one as it's the most complicated part. Tell them overall that this function will be called after Rocketsled suggests a new point in input space to try, x. The job of this function is to transform that x into a Workflow that can automatically run the function evaluation again. Again, walk them through line-by-line.
* Finally - put it all together. Put all the code together into ONE file, including the FireTask that does the function evaluation. Make sure this code is reproduced in the docs fully without the user having to open it. Anything that the user is expected to modify like db host, port, etc. goes near the top of the file - never in the middle of the file. Tell the user to modify these things in the examples directory where this one master file is located and try running it.
* As a postscript, tell people what to do next. Most notably, if they want to change the function that is being evaluated, they can modify that file, but if they move that file or reference external code, any code that's referenced must be part of the PYTHONPATH and installed. They can see FWS "comprehensive guide to firetasks" for more details.

**Comment by computron** [comment]
(that would be the main intro tutorial - it will be long, but it will actually tell people what's going on)

Optionally, you can also just have people run the one main file first (modifying the host/port of the database, etc. to get it working) before explaining what is going on. So step 1 can just be to get it running. Step 2 can be looking at every line in the code and having a sense of what's happening in those lines so people can make appropriate modifications.

**Comment by computron** [comment]
I would also remove auto_setup.py ...

**Comment by computron** [comment]
Also, at the end of the tutorials, you should refer people to the examples directory. The examples should contain more code comments and in-line explanations. Also, things like database name, host, port, etc. set up should be at the TOP of the file in a section clearly marked for the user to modify.

**Comment by ardunn** [comment]
@computron updated examples and changed around tutorial. got rid of auto_setup.

new tutorial is not super polished yet but I thought I'd get your thoughts on it. I tried to base it on the above comments but I made some pretty significant changes to the code so some are not relevant at this time. Have any opinions on the new tutorial?
