### ISSUE TITLE
General comment on code and examples

### ISSUE THREAD

**Issue by computron** [hackingmaterials/rocketsled#56]
A lot of the code will be difficult to newcomers because the code is not well-separated. For example:

rocketsled/examples/batch.py
is better than
rocketsled/examples/basic.py

Because in the batch.py, the workflow_creator is focused on code related to workflow creation. In the latter, the workflow creator is also defining X_dim - but it makes no sense to be defining X_dim inside workflow creator. X_dim would be something the user determines beforehand and defines as a global variable or some other thing like it (as you do in batch.py). The workflow creator function should only do workflow creation - any parameters that are not all about workflow creation should be gotten from elsewhere.

As a side note, I am not sure why X_dim can't just be auto-detected from the rocketsled database instead of needing to be passed in all the time.

**Comment by ardunn** [comment]
Examples reworked with more documentation and separation via a8edd5a3f450e49fb6efad40abb13cc71cc573da


@computron regarding X_dim: It can be detected from the database, but the user registering it with the db might introduce an additional step (maybe worth it though?): One way to go about this is to add a function specifically for adding the dimensions to the db:
```
# adds a document holding the dimensions to the db
add_dimensions(X_dims)
```

Opinions on this fix? Or whether to keep as is? Or perhaps a different solution?

**Comment by ardunn** [comment]
actually see #57

**Comment by ardunn** [comment]
This issue is obsolete, see links above
